swiftmailer:
    url: '%env(MAILER_URL)%'
    spool: 
        type: file
        path: '%kernel.project_dir%/var/spool'


# set limit for counte message and time
# php .\bin\console swiftmailer:spool:send --message-limit=10 --env=prod  
# php .\bin\console swiftmailer:spool:send --time-limit=10 --env=prod  
